/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useMemo } from 'react';
import { useGLTF } from '@react-three/drei';

export default function Ceiling({ isSelected, ...props }) {
  const { nodes, materials } = useGLTF('./models/parts144/Ceiling.glb');

  // Create a new material instance to avoid modifying the original material
  const highlightedMaterial = useMemo(() => {
    const material = materials['Oak wood'].clone();
    material.emissive.set('red');
    material.emissiveIntensity = 1;
    return material;
  }, [materials]);

  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube122.geometry}
        material={isSelected ? highlightedMaterial : materials['Oak wood']}
        position={[-0.016, 2.524, -1.028]}
      />
    </group>
  );
}

useGLTF.preload('./models/parts144/Ceiling.glb');