/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useMemo } from 'react';
import { useGLTF } from '@react-three/drei';

export default function DinetteBed({ isSelected, ...props }) {
  const { nodes, materials } = useGLTF('./models/parts144/DinetteBed.glb');

  // Create highlighted materials for each mesh
  const highlightedMaterial1 = useMemo(() => {
    const material = materials.STEP_ff00ff.clone();
    material.emissive.set('red');
    material.emissiveIntensity = 1;
    return material;
  }, [materials.STEP_ff00ff]);

  const highlightedMaterial2 = useMemo(() => {
    const material = materials['Material.002'].clone();
    material.emissive.set('red');
    material.emissiveIntensity = 1;
    return material;
  }, [materials['Material.002']]);

  return (
    <group {...props} dispose={null}>
      <group position={[-0.024, 0.828, -1.961]} >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Document001_1.geometry}
          material={isSelected ? highlightedMaterial1 : materials.STEP_ff00ff}
         
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Document001_2.geometry}
          material={isSelected ? highlightedMaterial2 : materials['Material.002']}
          
        />
      </group>
    </group>
  );
}

useGLTF.preload('./models/parts144/DinetteBed.glb');